### ISSUE TITLE
Execution failed for task ':tools:go-cli:distBinary'

### ISSUE THREAD

**Issue by lfzCarlosC** [openwhisk/openwhisk#1002]
## Environment details:

* vagrant 1.8.1   
*   OS Name:                   Microsoft Windows 7 Professional
* OS Version:                6.1.7601 Service Pack 1 Build 7601
* terminal : bash shell

## Steps to reproduce the issue:

1. git clone --depth=1 https://github.com/openwhisk/openwhisk.git
2. cd openwhisk/tools/vagrant
3. ./hello

## Provide the actual results and outputs:

```
output comes here

==> default: Successfully built 63bb4d1e5956
==> default: :tools:go-cli:tagImage
==> default: Executing 'docker tag -f whisk/go-cli whisk/go-cli:latest'
==> default: :tools:go-cli:pushImage
==> default:
==> default: SKIPPED
==> default: :tools:go-cli:removeBinary
==> default: :tools:go-cli:distBinary
==> default: Executing 'docker rm -f go-cli'
==> default: Executing 'mkdir /home/vagrant/openwhisk/tools/go-cli/../../bin/go-                                                                      cli/'
==> default: Executing 'docker run --name go-cli whisk/go-cli:latest'
==> default: Executing 'docker cp go-cli:/src/github.com/go-whisk-cli/build/. /h                                                                      ome/vagrant/openwhisk/tools/go-cli/../../bin/go-cli'
==> default: ln: failed to create symbolic link ‘/home/vagrant/openwhisk/bin/go-                                                                      cli/wsk’: Protocol error
==> default: :tools:go-cli:distBinary FAILED
==> default: FAILURE:
==> default: Build failed with an exception.
==> default: * Where:
==> default: Build file '/home/vagrant/openwhisk/tools/go-cli/build.gradle' line                                                                      : 31
==> default: * What went wrong:
==> default: Execution failed for task ':tools:go-cli:distBinary'.
==> default: >
==> default: Process 'command 'ln'' finished with non-zero exit value 1
==> default: * Try:
==> default: Run with
==> default: --stacktrace
==> default:  option to get the stack trace. Run with
==> default: --info
==> default:  or
==> default: --debug
==> default:  option to get more log output.
==> default: BUILD FAILED
==> default: Total time: 7 mins 58.614 secs
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.



## Additional information you deem important:
* issue happens only occasionally or under certain circumstances   
* changes you did or observed in the environment

**Comment by rabbah** [comment]
@csantanapr is it still possible to run vagrant without mounting a shared folder?

**Comment by csantanapr** [comment]
>@csantanapr is it still possible to run the openwhisk vagrant machine without mounting a shared folder?

The use case was not very useful and was bring a lot of confusing on having too many ways to setup, and tend to let people just workaround root cause problems.

We should not be using "ln" anywhere to have a chance to support windows natively, there are lot of developer that only have Windows as their dev workstation.

This `tools/go-cli/build.gradle` is incompatible with Windows by using "ln"
https://github.com/openwhisk/openwhisk/blob/master/tools/go-cli/build.gradle#L32
```
   String link_to_path = new File("${projectDir}/../../bin/go-cli/wsk").getCanonicalPath()
    String link_from_path = new File("${projectDir}/../../bin/go-cli/${go_osname}/${go_osarch}/wsk").getCanonicalPath()
    exec {
        executable "ln"
        args "-s", "${link_from_path}", "${link_to_path}"
    }
```

The strange thing is that we already inside the VM in vagrant and it work
https://github.com/openwhisk/openwhisk/blob/master/tools/vagrant/Vagrantfile#L134
```
  rm -r bin/wsk && rm -r bin/wskadmin
  (cd bin && sudo ln -s ../tools/cli/wsk wsk)
  (cd bin && sudo ln -s ../tools/cli/wskadmin wskadmin)
```

I guess if we use `sudo` it might work, the problem is that would cause problems, like mac trying to run with `sudo`

I think the quick fix is to just do a copy of the binary (using gradle not `cp` :-) ) , instead of `ln`
```
task copyTask(type: Copy) {
    from '${link_from_path}'
    into '${link_to_path}'
}
```

More elegant solution would be to write wrapper scripts wsk (bash) and wsk.bat, for the bash it will detect if linux or mac, and the arch, for windows will detect the arch and then delegate to the correct binary on the fly.

@mdeuser can you take this one since you are the one that has a Windows box and can test the propose fix with copyTask?
Why you think you have not hit this problem on your Windows workstation? maybe you created the symlink manually, and it's seating there making any subsequent calls to `ln` to be ignore/success

**Comment by csantanapr** [comment]
Hi @lfzCarlosC I have a PR #1019  under review that fixes this issue do you mind giving a try on your windows box and report if it now works?

```
git clone --depth=1 -b issue-1002 https://github.com/csantanapr/openwhisk.git
cd openwhisk/tools/vagrant
./hello
```
