### ISSUE TITLE
Update to Swift 3 GA

### ISSUE THREAD

**Issue by paulcastro** [openwhisk/openwhisk#1133]
Add experimental Swift 3 runtime that uses the latest snapshot that includes URLSession and integrated Dispatch.

**Comment by paulcastro** [comment]
Tested URLSession in an Ubuntu 15.10 VM and it can at least perform the httpGet.swift test.

**Comment by sjfink** [comment]
Four work items identified in discussion with @paulcastro 
* [ ] upgrade Swift 3 container
* [ ] make Swift 3 the default instead of 2.2
* [ ] remove all support for Swift 2.2.    This would mean adding a new error “Unsupported runtime: experimental Swift 2.2 is no longer supported.   Please recreate your action using Swift 3”.
* [ ] publish an openwhisk/swift3 base image on docker hub and pull that, rather than building the swift 3 implementation from swift.org (should improve build time)

**Comment by sjfink** [comment]
For the record, we understand that NSURLSession is still buggy so we include kitura.net for now.

**Comment by psuter** [comment]
Closed by #1325
