### ISSUE TITLE
deprecate node 0.12

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#1243]
proposal:

1) make it impossible to create new actions with kind node 0.12.7
2) execute all extant kind node 0.12 actions on the node 6 runtime.

**Comment by bjustin-ibm** [comment]
2 could likely be implemented by updating [DefaultRuntimeVersions.scala](https://github.com/openwhisk/openwhisk/blob/master/common/scala/src/main/scala/whisk/core/entity/DefaultRuntimeVersions.scala#L22) so that the `nodejs` kind is mapped to `nodejs:6`. It may also be worth renaming this trait to something more generic like `RuntimeMapping` or `ActionKindMapping`.

**Comment by cclauss** [comment]
Is this issue closed?
