### ISSUE TITLE
promote REST API documentation to first class

### ISSUE THREAD

**Issue by sjfink** [openwhisk/openwhisk#1286]
We get a lot of questions about how to use the REST API for OW.

Right now we have limited documentation, and it's nested in https://github.com/openwhisk/openwhisk/blob/master/docs/reference.md

Instead, promote it to a new top-level chapter (using the OW REST API) and fill in missing details.

**Comment by fe01134** [comment]
SImilar to to other runtimes and services we want to make sure that we have the Getting Started Tab on the runtime/console dashboard.  See:
 Bluemix Developer Guide:  https://new-console.stage1.ng.bluemix.net/docs/developing/index.html
          Getting Started Template and Guidelines  Read about "Adding the "Getting Started" tab to your service dashboard” https://new-console.stage1.ng.bluemix.net/docs/services/onboarding/index.html#add-getting-started-tab

I believe the team already does the format for Bluemix REST API Documentation (RECOMMEND)

   https://console.stage1.ng.bluemix.net/docs/cli/apidocs.html#apidocs

One thing I personally struggled with when using the CLI / API is authentication.  I tried creating a custom Alexa Skill from AWS to Open Whisk. So that we can provide Alexa developers another option other than Lambda.  While I was able to get Alexa to call my Node Red and Python Bluemix Runtimes. I was unable to figure it out using the Open Whisk API because we don't provide adequate guidance on creating the authentication request ( headers etc)  instead we immediately describe how to use the API without providing the crucial first step of authentication/securing.

You can find the Doc feedback/ defects that describe the issues in greater detail here
https://releaseblueprints.ibm.com/display/CLOUDOE/UC+50+-+Notifications

 https://jazzop27.rtp.raleigh.ibm.com:9443/ccm/web/projects/CloudOE#action=com.ibm.team.workitem.runSavedQuery&id=_8Q0EIDk5EeaBeKcqVao6Vg&filterAttribute=internalTags&filterValue=openwhisk&filterByExactMatch=true&tq=1479308399000

**Comment by csantanapr** [comment]
Thanks @fe01134 for the feedback

The section should address your concern on getting started using the API, from creating and invoking/firing actions/triggers and also use the CLI `-v` flag to inspect the http request that is doing under the hood.
