### ISSUE TITLE
Proposal: Plugin system for different runtimes

### ISSUE THREAD

**Issue by markusthoemmes** [openwhisk/openwhisk#1316]
## Problem statement

Currently we support a fixed number of runtimes in OpenWhisk "natively". That means a user can upload an artifact specific to the language (i.e. a code snipped) and we will treat it as needed by that language (compile it, run it).

While this is all good, the approach doesn't scale from a CI/CD point of view. We're currently hitting the 50 minute mark in Travis repeatedly and even with that off the table, our build times will just increase over time as we add new runtimes. Building the different runtimes, especially Swift currently, has a big impact on our overall build time. It also impacts first-time contributors as the time to "just deploy the system locally" increases.

## Proposed solution

We could add a plugin system for runtimes and only ship OpenWhisk with a default runtime (Node.js for example). We benefit from this in multiple ways:

1. Build and testtime for just the *core* system decreases. As we only test what's common for every language. I think it makes sense to define at least one language as being the default though, to facilitate end-to-end testing and have a better test-coverage for that core system.
2. It's easier for contributors to add new runtimes, as they likely don't have to touch the core components.

## Thoughts on design

To implement this we could make runtimes part of the configuration. That configuration would then include the different properties of each runtime, included in `Exec.scala` today.

The configuration needs to be able to tell the system which *image* to use and which properties to expect for each of the runtimes (Node.js for example takes `code`, Java takes a `.jar` file).

**Comment by domdom82** [comment]
Is there a way to add multiple travis builds in a pipeline kind of way?
I am wondering because there is (besides the number of runtimes) in general the natural problem of ever increasing number of tests which will by definition at some point hit a time limit that is unacceptable.

We are currently executing the majority of tests in one huge suite in `:tests:test` which is also a nuisance if you want to e.g. update just documentation (which should also be tested btw.)

So if we were able to split those into smaller but faster pieces - for example with a pluggable runtime, but not necessarily stop there - be awesome. 

If that does not work, my only other idea would be to split into multiple repos and assign one travis build for each repo and have them pick up one another.

**Comment by rabbah** [comment]
@markusthoemmes duplicate of https://github.com/openwhisk/openwhisk/issues/319? If you agree consolidate and close one.

**Comment by markusthoemmes** [comment]
Agreeing, commented under your issue. Closing.
