### ISSUE TITLE
Replace docker inspect with looking at config.json

### ISSUE THREAD

**Issue by perryibm** [openwhisk/openwhisk#1334]
`docker inspect` like `docker ps` empirically grabs a lock and is slow when the number of active containers is large even when inspecting a single container.  Speculating that docker does not use a multi-grain locking scheme.   Even when the number of containers is slow, this is a slowish call.  There is consensus to replace this by inspecting the config.json file directly in the way we obtain logs in an efficient manner by looking in `..../containers/HASH/`.

However, the configuration file has moved from config.json to config.v2.json when going from docker 9 to docker 12 so we will defer working on this until we have completed our transition.

**Comment by domdom82** [comment]
@rabbah @sjfink 
for less disruption: can we do a `docker version` at invoker startup to collect the server version and branch off into the config.json reader if version >= 1.12.x and just keep the old code otherwise? this would be like a feature-toggle and @perryibm would not have to wait until all systems are on 1.12.

we will probably need to check for kernel version, too. some security features only work on certain kernel levels.

**Comment by perryibm** [comment]
We are now fully on docker 1.12 and I'll start looking into this again.  The main issue is to note that there may need to be a retry for the config file (or a particular field) to appear as `docker run` is not instant and docker makes no promise about how started a container is (or daemon state) when the call returns.

**Comment by perryibm** [comment]
The code for this has been pushed and we are undergoing stress testing.  Because it's a fundamental change, I will keep this open until we see evidence that this is working as designed when under load.

**Comment by markusthoemmes** [comment]
Adopted.
