### ISSUE TITLE
Web action with http extension defining "OK" when body is missing from response 

### ISSUE THREAD

**Issue by rabbah** [openwhisk/openwhisk#2132]
Create a web action which doesn't return a "body" top level property and curl it as a web action with .http as the extension. It responds with "OK" which comes from the lower spray layer that binds a message to the status code 200.

**Comment by mdeuser** [comment]
What should be the response status code and body in this situation -  `.http` invocation of web action that does not return JSON with a `body` field?

**Comment by rabbah** [comment]
the defaults are:

- statusCode: 200
- body: empty
- headers: []

but the controller is sending body "OK" instead of the empty response.

**Comment by rabbah** [comment]
The fix will apply on this line: https://github.com/openwhisk/openwhisk/blob/master/core/controller/src/main/scala/whisk/core/controller/WebActions.scala#L243

**Comment by mhamann** [comment]
After talking a bit with @mdeuser, it seems like returning a 400 would be a good thing to do if the developer did not send the right format in the response from their web action.

Additionally, instead of returning an empty body, might it make sense to also return a string or something indicating that the action is misconfigured?

**Comment by mdeuser** [comment]
@rabbah - any concerns?

**Comment by rabbah** [comment]
is this strictly to cover the programmer when they fail to return `body` or an http action? if the absence of any fields, should this be treated as success of failure - since we define defaults.

i think this is more subtle and want to think it through some more.
i can imagine that such validation could happen inside an action with a validation middleware (thinking of an `express` like approach where the validation happens inside the action as user code and not in the controller.)

**Comment by browezilla** [comment]
Hi @rabbah . Just checking back in. We were hoping to finish this up this week so we can do our final promotion for Serverless Austin on Tuesday.  We don't have a strong opinion on this, but I guess I'm leaning toward your second comment so that we aren't in conflict with the defaults.

**Comment by rabbah** [comment]
I linked to the one line that requires a change for http. The fix is to complete(StatusCodes.OK, HttpEntity.Empty). It will need an obvious test. If someone wants to send a pr I'll be happy to review and merge. I may not get to it today.

**Comment by mdeuser** [comment]
@dubeejw - can you look into this fix.  thanks!

**Comment by rabbah** [comment]
Proposed patch in https://github.com/openwhisk/openwhisk/pull/2148/files.

**Comment by akrabat** [comment]
Just to double check, but there are quite a few status codes that don't need a body and at least one that mandates that you may not have a body (`204`). Does this change break the these situations as I wouldn't want my `204` changed to a `400`…

**Comment by rabbah** [comment]
The patch I proposed is to fix the case where a missing body resulted in a response of "OK". No when no body is present the response is no content as well. So it's consistent with the behavior you want.

**Comment by akrabat** [comment]
Ah, I see. There's a default text that's used if there's no body and that default text is "OK" for 200, which is nonsense.

**Comment by mdeuser** [comment]
One potentially common scenario.  A developer quickly creates a webaction from an existing action (i.e. set web-export annotation to true), but leaves the action logic alone.   When the webaction is invoked without an extension (defaults to .http), the response will contain JSON that does not have a `body`, but does have one or more fields - none of which are `statusCode` or `headers`.  Currently, the status code is 200 with no body, which may lead to some false positives regarding the actual action success.

In this developer-error scenario, I suppose this could be viewed as a content type mismatch.  The request expected a webaction HTTP response, but actual response was free form webaction JSON.  Since the webaction invocation extension is involved in specifying content type, a response that does not adhere to the request is mismatched.

**Comment by rabbah** [comment]
`return {statusCode: 200}`
`return {body: "..."}`
`return {headers: {"Access-Control-Allow-Origin": "*"}`
`return {}`

All are plausible and reasonable responses - which of these should be malformed?
It seems that trying to save the programmer from bad code is a separate concern better solved by a validation middleware (ala express) or tests.

**Comment by mdeuser** [comment]
I agree that issue at hand is how to alert the programmer to bad code.  Will middleware automatically handle the content type checks?  I was thinking it did not and that it was up to the express developer to enforce any content type restrictions.

From the sample snippets above, I don't think any of those are malformed; the `statusCode` will default to 200 when not specified and the `body` and `header` fields are optional with no defaults.

The malformed JSON, when returned for a webaction .http invocation, I'm thinking of is something like:
```
return { name: "fred", status: "success", fieldA: "valueA" }
```

**Comment by akrabat** [comment]
I suspect that it's reasonable to require an empty dictionary or at least one of  `headers`, `body` or `statusCode` for a non-empty dictionary from an `http` web action. 

On the flip side, any testing at all will show that you've made a mistake when you get this wrong…

**Comment by mdeuser** [comment]
Yeah, testing will reveal something is wrong in the scenario described above, but the 200 status code without any body may not be sufficient to quickly lead to a content type mismatch root cause.  In this scenario, the webaction's activation results don't directly call out the content type mismatch; so I think the only logging that would call this out would be in the OpenWhisk controller log - something the developer won't have access to.

**Comment by rabbah** [comment]
The issue was closed because the PR merged above fixes the "OK" bug for missing body. @mdeuser if you'd like to reopen the issue or create a new one to discuss whether to error on a missing code + body + headers, please do so.

For the record, I don't think you need access to the system logs to know what happened.

```
> cat t.js 
function main() {
return { name: "fred", status: "success", fieldA: "valueA" }
}

> wsk action create t t.js --web yes

> curl -k https://guest.openwhisk/default/t -v
*   Trying 192.168.99.100...
* Connected to guest.openwhisk (192.168.99.100) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_RC4_128_SHA
* Server certificate: *.openwhisk
> GET /default/t HTTP/1.1
> Host: guest.openwhisk
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.11.13
< Date: Wed, 19 Apr 2017 17:55:42 GMT
< Content-Length: 0
< Connection: keep-alive
< 
* Connection #0 to host guest.openwhisk left intact

> > lget
ok: got activation 472cc4dd39884e9381adfc6a04d4291d
{
    "namespace": "guest",
    "name": "t",
    "version": "0.0.1",
    "subject": "guest",
    "activationId": "472cc4dd39884e9381adfc6a04d4291d",
    "start": 1492624542934,
    "end": 1492624542941,
    "duration": 7,
    "response": {
        "status": "success",
        "statusCode": 0,
        "success": true,
        "result": {
            "fieldA": "valueA",
            "name": "fred",
            "status": "success"
        }
    },
    "logs": [],
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "guest/t"
        }
    ],
    "publish": false
}
```
