### ISSUE TITLE
Allow user to provide yaml in addition of json for wsk api create command

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk#2170]
The command `wsk api create --config-file CFG_FILE`
CFG_FILE containing API configuration in swagger JSON format

We should allow user to be able to import and export in yaml format, since downstream implementations of openwhisk apigateway like bluemix, will be providing a yaml to the user to edit, or user is using swagger tooling that support yaml.

**Comment by mdeuser** [comment]
Proposed changes:

1. Add a new option to the `wsk api get` CLI, such as `--format json | yaml`.  When not specified, it will default to `json`.  It will output the API per the format specification.  If the format type is neither JSON nor YAML, and command syntax error is given.

2. The `wsk api create --config-file FILE` command will now examine the file extension.  If the file ends in either .yml or .yaml, then the file is parsed as YAML and converted into JSON for command processing.  Otherwise, the file is treated as JSON.

**Comment by csantanapr** [comment]
@mdeuser I think looks OK.
I like to see that we auto detect extension file.

You think we don't need also a flag `--format yaml`? on create `wsk api create --config-file myapi.yaml --format yaml`

**Comment by mdeuser** [comment]
I was thinking that the import file extension - either `.yaml` or `.yml` -  would be sufficient for indicating YAML content; so no need for an explicit `--format` option.

**Comment by csantanapr** [comment]
ok if I have to choose I prefer file extension detection
