### ISSUE TITLE
update an entity which is not exist

### ISSUE THREAD

**Issue by tareqmamari** [openwhisk/openwhisk#220]
CLI successfully updated entities which are in fact not exist at all,

e.g. 
```
$ wsk action update iAmNotExist somecode.js
ok: updated action iAmNotExist
```

I think it should raise an error instead, shouldn't it ?

This apply to all other entities, besides, I could update an action with passing no parameters (e.g. code file) , is that right ?
e.g.
```
$ wsk action update iAmNotExist
ok: updated action iAmNotExist
```

**Comment by rabbah** [comment]
Both the `create` and `update` operation are PUT operations on their respective collection. The API guards the former so that an overwrite flag is required to update an entity if it already exists. This flag `?overwrite=true` is provided by the `update` operation. Hence the semantics of `update` is to create if entity does not exist else to update it. This is operating as designed.

**Comment by tareqmamari** [comment]
It is clear to me now, thanks Rabbah
