### ISSUE TITLE
Create a MD(markdown) version of OpenWhisk package introduction doc.

### ISSUE THREAD

**Issue by lzbj** [openwhisk/openwhisk#369]
Based on the existing package and other concepts introduction documents.
https://github.com/openwhisk/openwhisk/tree/master/docs

Compose a MD doc about how to create package and submit them to github.

**Comment by rabbah** [comment]
Do you mean just the latter (submit them to github)? Improving the docs for working with packages otherwise should complement and extend this https://github.com/openwhisk/openwhisk/blob/master/docs/packages.md#creating-a-package for example. 

There are synchronizing changes to be made to the Bluemix related docs from which these were generated. @csantanapr can point you to the appropriate process.

One thing to keep in mind is that packages do not need to be in this git repository. In fact as others create packages they surely won't be.

**Comment by mrutkows** [comment]
I believe David plans to create documentation for each of the individual packages and show how they can be used (within the directories of the actions/feeds themselves).  It would be good to have standalone docs for when we split out their dir. structure into new repos.

**Comment by rabbah** [comment]
OK - The source for the docs in the referenced folder is this actually from another project, see https://github.com/IBM-Bluemix/docs/tree/master/openwhisk. I speculate that additional docs will be useful for Bluemix as well and should be coordinated so that they can be used there as well.

**Comment by mrutkows** [comment]
OK - So the docs in https://github.com/IBM-Bluemix/docs/tree/master/openwhisk are the "masters" from which the open ones get generated (i.e., in the path form your first link... https://github.com/openwhisk/openwhisk/tree/master/docs)?  So what you are saying is we need to author is such a way so both benefit?  Also, is there linkage between the 2? or are they now separated?

**Comment by rabbah** [comment]
deferring to @csantanapr.

**Comment by lzbj** [comment]
Correct, so I can start the work, and submit them to correct repo when necessary.

**Comment by lzbj** [comment]
@mrutkows , this doc:
https://github.com/openwhisk/openwhisk/blob/master/docs/catalog.md
so we need to split this doc, for each package folder once we create new repo for packages?

**Comment by csantanapr** [comment]
I agree if the catalog will be split into different repos, each repo should have a top level README.md and a docs/ directory

**Comment by csantanapr** [comment]
each package now has a top level README including packages inside catalog
