### ISSUE TITLE
"wsk namespace" should allow to set the current namespace

### ISSUE THREAD

**Issue by l2fprod** [openwhisk/openwhisk#455]
In the Bluemix context, given the names for namespaces are made of a contact of org+bluemix space, I often rely on `wsk namespace list` to find the name of a particular namespace.

So I do:

```
wsk namespace list
```

But then to set the current namespace, I have to do:

```
wsk property set --namespace fred@ibm_space
```

Instead I'd like to do

```
wsk namespace set
```

`wsk namespace get` is also a bit counter intuitive as I would expect it to give me the current namespace but instead it sounds equivalent to `wsk list`.

**Comment by mbehrendt** [comment]
this is good feedback -- @csantanapr , what do you think?

**Comment by rabbah** [comment]
note that we previously had this behavior and changed it to current model based on feedback as well ;)

**Comment by csantanapr** [comment]
Hum right now, I think we keep the short memory to the user to only "to set any configuration for the cli itself only need to remember one spot to do it" `wsk property`

Also `wsk namespace set ...` feels wrong as user would think they are changing something on the namespace itself on the backend (permanent), and not a setting of the current installation of the cli`

Switching the current/default namespace that cli commands will use feels more a global config for the current install of cli, and I think it's more proper `wsk property set` 

At the same time I'm not too in love of the "set" and "get" terminology, maybe because of my past work on mfpdev-cli :smile:

We had global context and local context, and used the term `config` it matches 'git' and 'npm' these were kind of tools we follow pattern:

`mfpdev app config <key> <value>` (sets a config key for the app context)
`mfpdev app config <key>` (prints/gets the value for config key)
`mfpdev app config --list` (prints all the available keys with corresponding human description to get or set)
`mfpdev config <key> <value>` (sets a global configuration key for the CLI, value affects all commands)

We could have:
`wsk config ...` for cli settings
`wsk config namespace <new_namespace>` switch to new namespace for cli commands
`wsk list --namespaces` (lists all namespaces available)

**Comment by mrutkows** [comment]
Agree with Carlos ...
"Also wsk namespace set ... feels wrong as user would think they are changing something on the namespace itself on the backend (permanent), and not a setting of the current installation of the cli`".

The current behavior seems correct IMO

**Comment by mbehrendt** [comment]
i think the challenge is -- when using `wsk property set`, users won't know the syntax to use, so at a minimum the cli help for that command needs to be enhanced. i tend to like the `wsk namespace <verb>` syntax better, since it seems more direct to the user ('i want to change the namespace, so let me look at the sub-commands for `wsk namespace`). if there are concerns regarding the selection of the verb (`set` vs. something else), we can look at alternative proposals. which verbs would you feel better with?

**Comment by rabbah** [comment]
No longer relevant.

**Comment by datbui** [comment]
I believe would be good idea to present 'set-current' or 'change'  operation

```
wsk namespace set-current MY_NAMESPACE
wsk namespace change MY_NAMESPACE

```

Using . 
```
wsk property set --namespace fred@ibm_space

```
is not obviously.

**Comment by rabbah** [comment]
IBM's cli might allow something like this. For the Apache `wsk` CLI, the way to switch namespaces currently is to use `wsk property set -u <key>`. While what you suggest is possible, it would require an API extension.
