### ISSUE TITLE
Error: Cannot find module 'requestretry'

### ISSUE THREAD

**Issue by nicolelovecoding** [openwhisk/openwhisk#640]
I used request and got the error "Error: connect ETIMEDOUT."

And then use node-request-retry, the error message is "Error: Cannot find module 'requestretry'"

Any way to solve the issue?

**Comment by csantanapr** [comment]
Hi @nicolelovecoding 
It will helpful if you could provide steps to reproduce with some generic sample code.

I'm going to assume that you have a javascript action using default runtime nodejs 0.12
That you are using the request library provided by npm package request
trying to do some type of http request to a web service or web site.
And you are getting this error.

If you know that that the endpoint you are trying to reach is a valid one, and that it happens to timeout sometimes and you want to retry, you will need to write the logic, or use an npm package like [node-request-retry](https://www.npmjs.com/package/node-request-retry)

The problem is that the nodejs runtime only has a fix number of npm package already pre-installed and node-request-retry is not.

You can use an npm package that is not available by default by bundling 3rd party dependencies into your javascript action, take a look at the following article on how they use webpack to achieve this.
https://developer.ibm.com/openwhisk/2016/03/17/bundling-openwhisk-actions-with-webpack/

For reference on which packages are available for default you can look at the [source code](https://github.com/openwhisk/openwhisk/blob/master/core/nodejsAction/Dockerfile) or the [reference doc](https://github.com/openwhisk/openwhisk/blob/master/docs/reference.md#runtime-environment)

hope this helps, let us know how else we can help.

**Comment by nicolelovecoding** [comment]
My code is below:

const RequestRetry = require('node-request-retry');
const requestRetry = new RequestRetry();
const retryConditions = ['ETIMEDOUT'];

 function main(msg) {
     const n = msg.n || 1;
     var url;
     
     if (n % 2 == 1) 
        url = 'https://cal-1.stage1.mybluemix.net/suqare?n=' + n;
     else 
        url = 'https://cal-0.stage1.mybluemix.net/suqare?n=' + n;

     // request.get(url, function(error, response, body) {
         
     //     console.log(error);
     //     console.log(url);
     //     console.log(response);
     //     if (error)
     //        whisk.error();
     //     else
     //        whisk.done({msg: body});
     // });
     // return whisk.async();

    requestRetry.setRetryCodes(retryConditions);
    requestRetry.get(url, function(err, response, body) {
       if (response) {
          console.log('The number of request attempts: ' + response.attempts);
          whisk.done({msg: body});
       }
    });
    return whisk.async();
 }

And still get the error message "Error: Cannot find module 'node-request-retry'"

**Comment by csantanapr** [comment]
That error message is accurate the npm package 'node-request-retry' is not available.

This are the only npm packages pre-install and available:

- apn
- async
- body-parser
- btoa
- cheerio
- cloudant
- commander
- consul
- cookie-parser
- cradle
- errorhandler
- express
- express-session
- gm
- jade
- log4js
- merge
- moment
- mustache
- nano
- node-uuid
- oauth2-server
- process
- request
- rimraf
- semver
- serve-favicon
- socket.io
- socket.io-client
- superagent
- swagger-tools
- tmp
- watson-developer-cloud
- when
- ws
- xml2js
- xmlhttprequest
- yauzl

**Comment by sjfink** [comment]
Yes, node-request-retry is not installed -- as @csantanapr posted above, you can work around this as follows:

   The problem is that the nodejs runtime only has a fix number of npm package already pre-installe d and node-request-retry is not.

   You can use an npm package that is not available by default by bundling 3rd party dependencies into your javascript action, take a look at the following article on how they use webpack to achieve this.
https://developer.ibm.com/openwhisk/2016/03/17/bundling-openwhisk-actions-with-webpack/

**Comment by csantanapr** [comment]
I already provided an answer in my comment above https://github.com/openwhisk/openwhisk/issues/640#issuecomment-225763663

**Comment by sjfink** [comment]
reopening -- repurposing this as feature request to add requestretry to standard base image.

**Comment by sjfink** [comment]
OK -- I believe I have reproduced this problem.

**Comment by sjfink** [comment]
The problem is that your URL is an internal IBM address (in the stage1/YS1 bluemix).   Whisk actions can only talk to addresses in the public internet.    You'd need to deploy your endpoint in the public bluemix.

**Comment by nicolelovecoding** [comment]
Ok, thanks!
