### ISSUE TITLE
Relax global lock for docker pull operations to unblock invoker for blackbox actions

### ISSUE THREAD

**Issue by jeremiaswerner** [openwhisk/openwhisk#881]
## Environment details:
all

## Steps to reproduce the issue:

assuming 1 invoker environment
1.   invoke a nodejs action like `/whisk.system/samples/echo` (cold)
2.  invoke a blackbox action which the invoker needs to pull (cold)
3.  invoke a nodejs action like `/whisk.system/samples/echo` (warm)

## Provide the expected results and outputs:

Invoking the nodejs action the second time (warm) should be return immediately and not be blocked until the blackbox action is pulled.

## Provide the actual results and outputs:

Currently the invoker waits and is locked until the blackbox image is pulled.

**Comment by perryibm** [comment]
The context for this is that docker 0.9 under load with concurrent operations (3+ threads) leads to docker daemon hangs and soft kernel panics.  Because of that, we maintain stability by serializing docker operations when issued from the invoker.  Docker 1.11.2 or 1.12 may change this as some of these bugs have been addressed.  Meanwhile, most operations must remain serial.  For this issue, the question is whether `docker pull` can be exempt from the lock without destabilizing the system.

**Comment by rabbah** [comment]
@jeremiaswerner close? We promoted this fix already.
