### ISSUE TITLE
Activation List does not Throw an Error if a Namespace is Provided

### ISSUE THREAD

**Issue by dubeejw** [openwhisk/openwhisk#935]
## Environment details:

Any deployment
Go CLI

## Steps to reproduce the issue:

1.   wsk activation list /whisk.system/ -i -d

## Provide the expected results and outputs:

An error should occur if a namespace is passed to the CLI.

## Provide the actual results and outputs:

An error does not occur if a namespace is provided.

**Comment by rabbah** [comment]
The namespace on activation list should be ignored - all activations are stored in the default namespace for a subject. This is true for activation poll as well. If you pass the namespace to the API call you will get back an empty list. Suggest either disabling the feature in the cli, generating a warning, or masking it (I think the Python cli is doing the last of these).

**Comment by dubeejw** [comment]
@rabbah, if a namespace is provided for activation list or poll, that namespace is passed via an &name argument to the backend. Current, this behavior occurs for both CLIs.

**Comment by dubeejw** [comment]
Are you suggesting to get rid of the &name parameter from the URL?

**Comment by rabbah** [comment]
You omitted the leading slash on the namespace - that's why you're seeing the `name` query parameter in the URL.

`wsk activation list /whisk.system` vs `wsk -v activation list whisk.system` the latter filters activations for the given entity name.

My comment - to clarify - means that if you have a default namespace `/A` and a second namespace `/A_dev`, doing this `wsk activation list /A_dev` will yield `[]` because all activations for the same subject are in the default namespace `/A`. If you don't own the namespace then you won't be authorized for it, of course.
